### ISSUE TITLE
West Virginia licenses not handled correctly

### ISSUE THREAD

**Issue by plowman** [postmates/DLNValidation#9]
I recently encountered a WV license in the wild of the form [A-Z]{1}[0-9]{6} which does not match the indicated pattern of `'WV': r'^[0-9]{7}$'`. I was sent a picture of it, so I'm confident this is the correct pattern, but obviously I can't share it with you.

Other sources which suggest this is a real pattern:
* [WV Sample License](https://apps.wv.gov/DMV/SelfService/DrivingRecord), which is "Y999999"
* [The source for your work](http://www.deverusdemos.com/Help/FlashHelp/Search_Types/Formats_for_MVR_license_numbers.htm), which says WV license are "7 characters", which seems to mean "alphanumeric characters".

So the pattern should probably be updated to be something like `'WV': r'^[0-9]{7}$|^[a-z]{1}[0-9]{6}$'`

Anyway, if you're accepting PR's, I'm happy to create one. Thanks!

**Comment by kroo** [comment]
[ADR claims](http://adr-inc.com/PDFs/State_DLFormats.pdf) West Virginia follows one of two formats:
 - 7 Numeric
 - 1-2Alpha+5-6Numeric

**Comment by samstr** [comment]
Please post a PR and we will review. Well spotted.

**Comment by samstr** [comment]
Thanks so much for contributing!
